name: Node CI

on:
  push:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false

    - uses: actions/setup-node@v4
      with:
        node-version-file: .nvmrc

    - name: Start LocalStack
      run: |
        pip install awscli-local
        docker run -d --name localstack \
          -p 4566:4566 \
          -e SERVICES=sqs \
          localstack/localstack:latest

        echo "Waiting for LocalStack startup..."
        timeout 30 bash -c 'until curl -sf http://localhost:4566/_localstack/health; do sleep 1; done'
        echo "Startup complete"
        awslocal sqs create-queue --queue-name sample-queue

    - run: yarn install --immutable
    - run: yarn build
    - run: yarn lint
    - run: yarn test

